-- Phase 76b (Issue #76) — the four system-role templates: Inhaber, Salonmanager,
-- Personalabteilung, Ausbilder.
--
-- DATA ONLY: no table, column, index, type or constraint is created, altered or dropped
-- (`prisma migrate diff` against the migration history stays empty). IDEMPOTENT: inserted with
-- ON CONFLICT ("id") DO NOTHING, so a replay creates no row and changes nothing. These four rows
-- assign nothing to anyone — no "RoleAssignment" row, no "AuditLog" row (AK-76b-8): a template is
-- adopted by a customer only through the existing `POST /api/v1/roles/:id/copy` endpoint.
--
-- Code identifies these rows by id only (apps/api/src/contexts/platform/system-roles.ts); a drift
-- test (src/__tests__/system-role-templates-migration.test.ts) proves the migrated rows equal
-- SYSTEM_ROLE_PERMISSIONS there, in catalog order. Changing a template later means a NEW migration
-- plus a code change here — never a hand-edit of this file or of the 75b migration.

INSERT INTO "AccessRole" ("id", "tenantId", "name", "nameKey", "permissions", "createdAt", "updatedAt")
VALUES
  ('00000000-0000-4000-8000-00000000a004', NULL, 'Inhaber', 'inhaber', ARRAY[
      'employee:read:EIGENE',
      'employee:read:ZUGEWIESEN',
      'employee:create:ZUGEWIESEN',
      'employee:update:ZUGEWIESEN',
      'employee:manage-access:ZUGEWIESEN',
      'employee:anonymize:ZUGEWIESEN',
      'employee:import:ZUGEWIESEN',
      'employee:update-avatar:EIGENE',
      'employee:update-avatar:ZUGEWIESEN',
      'contract:read:EIGENE',
      'contract:read:ZUGEWIESEN',
      'contract:update:ZUGEWIESEN',
      'tenant-settings:read:ZUGEWIESEN',
      'tenant-settings:update:ZUGEWIESEN',
      'api-key:manage:ZUGEWIESEN',
      'audit-log:read:ZUGEWIESEN',
      'holiday:manage:ZUGEWIESEN',
      'salon:read:ZUGEWIESEN',
      'salon:manage:ZUGEWIESEN',
      'role:read:ZUGEWIESEN',
      'role:manage:ZUGEWIESEN',
      'role-assignment:manage:ZUGEWIESEN',
      'time-entry:read:EIGENE',
      'time-entry:read:ZUGEWIESEN',
      'time-entry:create:EIGENE',
      'time-entry:create:ZUGEWIESEN',
      'time-entry:update:EIGENE',
      'time-entry:update:ZUGEWIESEN',
      'time-entry:delete:EIGENE',
      'time-entry:delete:ZUGEWIESEN',
      'time-entry:revalidate:ZUGEWIESEN',
      'time-entry:import:ZUGEWIESEN',
      'retro-request:read:EIGENE',
      'retro-request:read:ZUGEWIESEN',
      'retro-request:create:EIGENE',
      'retro-request:create:ZUGEWIESEN',
      'retro-request:approve:ZUGEWIESEN',
      'presence-source:manage:ZUGEWIESEN',
      'terminal:manage:ZUGEWIESEN',
      'leave-request:read:EIGENE',
      'leave-request:read:ZUGEWIESEN',
      'leave-request:create:EIGENE',
      'leave-request:create:ZUGEWIESEN',
      'leave-request:approve:ZUGEWIESEN',
      'leave-request:correct:ZUGEWIESEN',
      'leave-request:attest:ZUGEWIESEN',
      'leave-request:cancel:EIGENE',
      'leave-request:cancel:ZUGEWIESEN',
      'section9:read:EIGENE',
      'section9:read:ZUGEWIESEN',
      'section9:upload:EIGENE',
      'section9:upload:ZUGEWIESEN',
      'section9:decide:ZUGEWIESEN',
      'leave-entitlement:read:EIGENE',
      'leave-entitlement:read:ZUGEWIESEN',
      'leave-entitlement:update:ZUGEWIESEN',
      'leave-config:read:ZUGEWIESEN',
      'leave-config:manage:ZUGEWIESEN',
      'company-shutdown:manage:ZUGEWIESEN',
      'vocational-school:read:EIGENE',
      'vocational-school:read:ZUGEWIESEN',
      'vocational-school:manage:ZUGEWIESEN',
      'overtime:read:EIGENE',
      'overtime:read:ZUGEWIESEN',
      'overtime:settle:ZUGEWIESEN',
      'overtime:set-opening-balance:ZUGEWIESEN',
      'month-close:read:ZUGEWIESEN',
      'month-close:close:ZUGEWIESEN',
      'month-close:unlock:ZUGEWIESEN',
      'month-close:close-year:ZUGEWIESEN',
      'shift:read:EIGENE',
      'shift:read:ZUGEWIESEN',
      'shift:plan:ZUGEWIESEN',
      'shift-config:manage:ZUGEWIESEN',
      'shift-pattern:read:EIGENE',
      'shift-pattern:read:ZUGEWIESEN',
      'shift-pattern:update:ZUGEWIESEN',
      'availability:read:EIGENE',
      'availability:read:ZUGEWIESEN',
      'availability:update:EIGENE',
      'availability:update:ZUGEWIESEN',
      'integration:manage:ZUGEWIESEN',
      'report:read:ZUGEWIESEN',
      'report:export:EIGENE',
      'report:export:ZUGEWIESEN',
      'report:notify:ZUGEWIESEN',
      'team-overview:read:ZUGEWIESEN'
    ]::text[], NOW(), NOW()),
  ('00000000-0000-4000-8000-00000000a005', NULL, 'Salonmanager', 'salonmanager', ARRAY[
      'employee:read:ZUGEWIESEN',
      'time-entry:read:ZUGEWIESEN',
      'time-entry:create:ZUGEWIESEN',
      'time-entry:update:ZUGEWIESEN',
      'time-entry:delete:ZUGEWIESEN',
      'time-entry:revalidate:ZUGEWIESEN',
      'retro-request:read:ZUGEWIESEN',
      'retro-request:create:ZUGEWIESEN',
      'retro-request:approve:ZUGEWIESEN',
      'leave-request:read:ZUGEWIESEN',
      'leave-request:create:ZUGEWIESEN',
      'leave-request:approve:ZUGEWIESEN',
      'leave-request:attest:ZUGEWIESEN',
      'leave-request:cancel:ZUGEWIESEN',
      'section9:read:ZUGEWIESEN',
      'section9:upload:ZUGEWIESEN',
      'section9:decide:ZUGEWIESEN',
      'leave-entitlement:read:ZUGEWIESEN',
      'vocational-school:read:ZUGEWIESEN',
      'shift:read:ZUGEWIESEN',
      'shift:plan:ZUGEWIESEN',
      'shift-pattern:read:ZUGEWIESEN',
      'availability:read:ZUGEWIESEN',
      'team-overview:read:ZUGEWIESEN'
    ]::text[], NOW(), NOW()),
  ('00000000-0000-4000-8000-00000000a006', NULL, 'Personalabteilung', 'personalabteilung', ARRAY[
      'employee:read:ZUGEWIESEN',
      'employee:create:ZUGEWIESEN',
      'employee:update:ZUGEWIESEN',
      'employee:update-avatar:ZUGEWIESEN',
      'contract:read:ZUGEWIESEN',
      'contract:update:ZUGEWIESEN',
      'leave-request:read:ZUGEWIESEN',
      'section9:read:ZUGEWIESEN',
      'leave-entitlement:read:ZUGEWIESEN',
      'leave-entitlement:update:ZUGEWIESEN',
      'vocational-school:read:ZUGEWIESEN',
      'overtime:read:ZUGEWIESEN',
      'month-close:read:ZUGEWIESEN'
    ]::text[], NOW(), NOW()),
  ('00000000-0000-4000-8000-00000000a007', NULL, 'Ausbilder', 'ausbilder', ARRAY[
      'employee:read:ZUGEWIESEN',
      'time-entry:read:ZUGEWIESEN',
      'leave-request:read:ZUGEWIESEN',
      'vocational-school:read:ZUGEWIESEN',
      'shift:read:ZUGEWIESEN'
    ]::text[], NOW(), NOW())
ON CONFLICT ("id") DO NOTHING;
