/**
 * Phase 73-08 functional.spec.ts — the canonical happy-path suite (D-11).
 *
 * Consolidates the non-overlapping content from the six pre-Phase-73 audit
 * specs that were deleted in 73-08:
 *
 *   - ui-audit.spec.ts          (sidebar + mobile shell render)
 *   - ux-quality.spec.ts        (modal closes on Escape, save confirmation)
 *   - ux-design-audit.spec.ts   (primary actions reachable from each page)
 *   - dynamic-audit.spec.ts     (pages render with content, no horizontal overflow)
 *   - ui-quality.spec.ts        (advisory-only — covered by Phase 75 visual regression)
 *   - visual-audit.spec.ts      (screenshot-only — covered by Phase 75)
 *
 * Anything more specific than a smoke check belongs in a domain spec:
 *   - clock-in / clock-out      → core-flows.spec.ts
 *   - time-entry CRUD           → time-entries-flow.spec.ts
 *   - leave-request flow        → leave-flow.spec.ts
 *   - admin settings            → admin-settings-flow.spec.ts
 *   - month close               → monatsabschluss.spec.ts
 *   - accessibility violations  → accessibility.spec.ts + axe-scan.spec.ts
 *
 * Conventions (Phase 73 rules):
 *   - `from "../fixtures"` (Plan 73-02 tenant fixture; per-test isolation D-04).
 *   - `getByTestId(...)` for every interactive element (Plans 73-03/04/05).
 *   - NO `page.waitForTimeout()` (Plan 73-06 ESLint rule).
 *   - No `.only`, no committed debug logging.
 */
import { test, expect } from "../fixtures";
import type { TestTenant } from "../fixtures";
import type { Page } from "@playwright/test";

const TEST_PASSWORD = "test1234";

/**
 * UI login through the public /login form. Mirrors leave-flow.spec.ts so the
 * happy-path here exercises the same shell as the domain specs.
 */
async function loginAsTenantAdmin(page: Page, tenant: TestTenant): Promise<void> {
  await page.goto("/login");
  await page.getByLabel("E-Mail").fill(`admin@${tenant.tenantId}.test`);
  await page.getByLabel("Passwort", { exact: true }).fill(TEST_PASSWORD);
  await page.getByRole("button", { name: /anmelden/i }).click();
  await page.waitForURL(/\/(dashboard|time-entries|leave|$)/, { timeout: 10_000 });
}

test.describe("Functional — happy paths across primary surfaces", () => {
  test.describe("Dashboard", () => {
    test("renders timer card + greeting after login", async ({ page, tenant }) => {
      await loginAsTenantAdmin(page, tenant);
      await page.goto("/dashboard");

      // Timer card is the dashboard hero (Phase 49.4). It always exposes
      // either an Einstempeln or Ausstempeln button — fail loudly if neither
      // mounts (covers the "no empty pages" advisory from dynamic-audit).
      const stempelBtn = page.getByRole("button", { name: /(Ein|Aus)stempeln/ });
      await expect(stempelBtn.first()).toBeVisible({ timeout: 10_000 });

      // Greeting at the top of the page proves the auth-store hydrated and
      // the user data resolved (Guten Morgen/Tag/Abend, ...).
      await expect(page.getByText(/Guten (Morgen|Tag|Abend)/)).toBeVisible();
    });

    test("primary clock action is reachable above the fold", async ({ page, tenant }) => {
      // Merged from ux-design-audit.spec.ts "critical actions reachable within 2 clicks"
      // — clock-in is the headline primary action; if it isn't visible the
      // dashboard hero is broken.
      await loginAsTenantAdmin(page, tenant);
      await page.goto("/dashboard");

      const stempelBtn = page.getByRole("button", { name: /(Ein|Aus)stempeln/ }).first();
      await expect(stempelBtn).toBeVisible({ timeout: 10_000 });

      // Above the fold = within the first 800px (covers both desktop + tablet
      // viewports configured in playwright.config.ts).
      const box = await stempelBtn.boundingBox();
      expect(box).not.toBeNull();
      expect(box!.y).toBeLessThan(800);
    });
  });

  test.describe("Sidebar navigation", () => {
    test("primary nav links route to the expected URLs", async ({ page, tenant }) => {
      await loginAsTenantAdmin(page, tenant);
      await page.goto("/dashboard");

      // Sidebar testid surface (Phase 73-05). `nav-{slug}` is generated by
      // Sidebar.svelte's `navSlug(href)` helper — keys never drift from the
      // route table.
      await expect(page.getByTestId("sidebar")).toBeVisible();
      await expect(page.getByTestId("sidebar-brand")).toBeVisible();

      const targets = [
        { testid: "nav-time-entries", url: /\/time-entries/ },
        { testid: "nav-leave", url: /\/leave/ },
        { testid: "nav-reports", url: /\/reports/ },
        { testid: "nav-dashboard", url: /\/dashboard/ },
      ];

      for (const t of targets) {
        await page.getByTestId(t.testid).click();
        await expect(page).toHaveURL(t.url);
      }
    });

    test("sidebar foot shows user info + logout (D-11 sidebar smoke)", async ({ page, tenant }) => {
      // Merged from ui-audit.spec.ts "sidebar foot user-info is visible".
      await loginAsTenantAdmin(page, tenant);
      await page.goto("/dashboard");

      await expect(page.getByTestId("sidebar-user-menu")).toBeVisible();
      await expect(page.getByTestId("sidebar-logout")).toBeVisible();
    });
  });

  test.describe("Zeiterfassung surface", () => {
    test("page anchors + add button are visible", async ({ page, tenant }) => {
      await loginAsTenantAdmin(page, tenant);
      await page.goto("/time-entries");

      // Surface anchors from Phase 73-03.
      await expect(page.getByTestId("time-entries-page")).toBeAttached();
      await expect(page.getByTestId("time-entries-add")).toBeVisible();
      await expect(page.getByTestId("time-entries-view-tabs")).toBeVisible();
    });
  });

  test.describe("Leave (Urlaub) surface", () => {
    test("page anchors + KPI row + new-request button are visible", async ({ page, tenant }) => {
      await loginAsTenantAdmin(page, tenant);
      await page.goto("/leave");

      // Surface anchors from Phase 73-04.
      await expect(page.getByTestId("leave-page")).toBeAttached();
      await expect(page.getByTestId("leave-new-request")).toBeVisible();
      await expect(page.getByTestId("leave-balance")).toBeVisible();
      await expect(page.getByTestId("leave-view-tabs")).toBeVisible();
    });

    test("leave-form modal closes on Escape (Modals UX contract)", async ({ page, tenant }) => {
      // Merged from ux-quality.spec.ts "modals can be closed with Escape key".
      // The leave form is the only modal that ships with a stable testid in
      // every tenant — admin/special-leave needs seed data that the fresh
      // bootstrap tenant doesn't provide.
      await loginAsTenantAdmin(page, tenant);
      await page.goto("/leave");
      await page.getByTestId("leave-new-request").click();

      const form = page.getByTestId("leave-form");
      await expect(form).toBeVisible();
      await page.keyboard.press("Escape");
      await expect(form).toBeHidden({ timeout: 2000 });
    });
  });

  test.describe("Reports surface", () => {
    test("reports page mounts with at least one report card", async ({ page, tenant }) => {
      await loginAsTenantAdmin(page, tenant);
      await page.goto("/reports");

      // Reports page mounts the DATEV + Lohnabrechnung KPI rows + cards.
      // We don't assert on specific content (depends on tenant data) — just
      // that the page mounted with reports visible (covers "no empty pages").
      await expect(page.getByText(/DATEV/i).first()).toBeVisible({ timeout: 10_000 });
    });
  });

  test.describe("Admin System surface", () => {
    test("admin/system page mounts with documented testid", async ({ page, tenant }) => {
      // Merged from ui-audit.spec.ts "admin system page loads all sections".
      // Trimmed to the testid contract emitted by Phase 73-05.
      await loginAsTenantAdmin(page, tenant);
      await page.goto("/admin/system");

      await expect(page.getByTestId("admin-system-page")).toBeAttached();
    });
  });

  test.describe("Cross-page sanity", () => {
    test("primary app pages render with non-trivial content", async ({ page, tenant }) => {
      // Merged from dynamic-audit.spec.ts "no empty pages (all have content)"
      // and ui-audit.spec.ts page-load smokes. Walks the same set of pages
      // covered by accessibility.spec.ts so coverage is consistent.
      await loginAsTenantAdmin(page, tenant);

      const pages = ["/dashboard", "/time-entries", "/leave", "/reports", "/settings"];

      for (const url of pages) {
        await page.goto(url);
        // Wait for the page to have meaningful body content. 50 chars is the
        // same threshold the deleted dynamic-audit.spec.ts used.
        await page.waitForFunction(() => document.body.innerText.trim().length >= 50, null, {
          timeout: 5_000,
        });
      }
    });

    test("dashboard has no horizontal overflow on desktop viewport", async ({ page, tenant }) => {
      // Merged from dynamic-audit.spec.ts "no horizontal scrollbar on desktop"
      // — kept just for the dashboard (the page most prone to grid blow-out).
      await loginAsTenantAdmin(page, tenant);
      await page.goto("/dashboard");

      // Wait for the page to settle before measuring (timer card hydrates async).
      await expect(page.getByRole("button", { name: /(Ein|Aus)stempeln/ }).first()).toBeVisible({
        timeout: 10_000,
      });

      const hasHScroll = await page.evaluate(() => {
        return document.documentElement.scrollWidth > document.documentElement.clientWidth + 1;
      });
      expect(hasHScroll).toBe(false);
    });
  });

  // Phase 110 follow-up: the visual-regression suite (visual.spec.ts) now seeds every test
  // tenant's admin as "already acknowledged the newest release note" so the auto-opening
  // WhatsNewPanel drawer doesn't sit over every screenshot baseline (see visual-seed.ts's
  // "2b. Acknowledge the newest release note" step). That means the drawer's auto-open behavior
  // itself is no longer exercised anywhere at the browser level — this describe block is that
  // coverage. Kept out of visual.spec.ts on purpose: asserting on a mid-animation drawer via
  // `toHaveScreenshot()` would be flaky (the drawer slides in), so this only checks visibility
  // via `getByRole`/`aria-label`, which Playwright's auto-waiting handles independently of the
  // open/close transition.
  test.describe("What's-New drawer (Phase 110)", () => {
    test("auto-opens once for a fresh user and can be dismissed", async ({ page, tenant }) => {
      // `tenant` fixture creates a brand-new admin per test (Plan 73-02, D-04 isolation), so
      // `User.lastSeenReleaseVersion` is null here — exactly the "never seen a release" state
      // the auto-open `$effect` in `(app)/+layout.svelte` reacts to.
      await loginAsTenantAdmin(page, tenant);
      await page.goto("/dashboard");

      const panel = page.getByRole("complementary", { name: "Was ist neu" });
      // An older/local API image can serve an empty release-notes corpus (AK-06 fail-silent
      // contract in release-notes.ts) — in that case there is nothing to auto-open and this
      // assertion would hang. Skip gracefully rather than asserting a false negative.
      const opened = await panel
        .waitFor({ state: "visible", timeout: 10_000 })
        .then(() => true)
        .catch(() => false);
      test.skip(!opened, "No release notes baked into this image — nothing to auto-open.");

      await page.getByRole("button", { name: "Schließen" }).click();
      await expect(panel).not.toBeVisible();
      // Not asserting on a post-dismiss reload here: markReleaseNotesSeen() persists the
      // acknowledgement via a fire-and-forget PUT (apps/web/src/lib/stores/release-notes.ts),
      // so reloading immediately after the click races that request rather than testing
      // anything deterministic. Server-side persistence of the marker is covered by
      // apps/api/src/__tests__/release-notes.test.ts.
    });
  });
});
