// Phase 77 Plan 04 — /api/v1/work-events route stubs (WORKEVENT-V19-01).
//
// CRITICAL DESIGN CONSTRAINT (PITFALLS.md E-1/E-2/E-3):
// /mine and / (management) are STRUCTURALLY SEPARATE endpoints. No role-branched
// scoping on a single endpoint — that pattern caused the v1.8.12 cross-employee
// leak. Self-view: GET /mine, always self-scoped from req.user.employeeId,
// ignores any ?employeeId= query param. Management: GET / + POST/PATCH/DELETE,
// requireRole("ADMIN", "MANAGER"), supports ?employeeId= filter.
//
// Phase 79 fills the handler bodies. This phase ships the route plumbing only —
// every handler returns 501 Not Implemented with a German message.
//
// Payload validation (Phase 79): workEventPayloadSchema.parse(req.body.payload)
// at handler entry. See ./work-event-payload-schema.ts.
//
// Adapter for Saldo reads (Phase 78): loadWorkEventsForRange(prisma, employeeId,
// from, to). See ../utils/work-event.ts.

import { FastifyInstance } from "fastify";
import { z } from "zod";
import { requireAuth, requireRole } from "../middleware/auth";
import { config } from "../config";
import { WorkEventType, WorkEventSource, Prisma } from "@clokr/db";
import { workEventPayloadSchema } from "./work-event-payload-schema";
import {
  assertMonthNotLocked,
  LockedMonthError,
  LOCKED_MONTH_ERROR_DE,
} from "../utils/locked-month";
import {
  assertClassificationAllowed,
  ClassificationNotAllowedError,
} from "../utils/work-event-rules";
import { getTenantTimezone } from "../utils/timezone";

const isTest = config.NODE_ENV === "test";
const READ_RATE_LIMIT = { max: isTest ? 1000 : 100, timeWindow: "1 minute" };
const WRITE_RATE_LIMIT = { max: isTest ? 1000 : 20, timeWindow: "1 minute" };

// ── Phase 79 Plan 03 — mutation schemas + German error constants ───────────
// REVISION (B1): source uses z.nativeEnum(WorkEventSource) so the full Prisma
// enum domain {PATTERN, MANUAL, AUTO} is accepted. A bare z.enum(["MANUAL",
// "AUTO"]) would silently reject PATTERN rows generated by the cron path.
const createBodySchema = z.object({
  employeeId: z.string().uuid("employeeId muss eine UUID sein"),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "date muss im Format YYYY-MM-DD sein"),
  type: z.nativeEnum(WorkEventType),
  source: z.nativeEnum(WorkEventSource).optional().default(WorkEventSource.MANUAL),
  workedMinutes: z
    .number()
    .int()
    .min(0)
    .max(24 * 60),
  expectedMinutes: z
    .number()
    .int()
    .min(0)
    .max(24 * 60)
    .nullable()
    .optional(),
  payload: z.unknown().optional(),
  note: z.string().max(2000).nullable().optional(),
});

const idParamSchema = z.object({
  id: z.string().uuid("id muss eine UUID sein"),
});

// PATCH body — `type` is intentionally absent from the writable shape because
// it participates in @@unique([employeeId, date, type]); mutating it would
// silently re-key the row. We surface a 400 with TYPE_IMMUTABLE_DE if the
// client tries to set it (detected via updateBodyDetectTypeSchema below).
//
// REVISION (B1): mirror createBodySchema — full Prisma enum domain.
const updateBodySchema = z.object({
  date: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "date muss im Format YYYY-MM-DD sein")
    .optional(),
  source: z.nativeEnum(WorkEventSource).optional(),
  workedMinutes: z
    .number()
    .int()
    .min(0)
    .max(24 * 60)
    .optional(),
  expectedMinutes: z
    .number()
    .int()
    .min(0)
    .max(24 * 60)
    .nullable()
    .optional(),
  payload: z.unknown().optional(),
  note: z.string().max(2000).nullable().optional(),
});

// Used to surface the "type cannot be changed" error explicitly before the
// general body parse (which would silently strip the unknown `type` key).
const updateBodyDetectTypeSchema = z.object({ type: z.unknown().optional() });

// ── Module-level German error constants ────────────────────────────────────
const DUPLICATE_WORK_EVENT_DE = "Eintrag existiert bereits für diesen Tag und Typ.";
const EMPLOYEE_NOT_FOUND_DE = "Mitarbeiter nicht gefunden";
const TYPE_IMMUTABLE_DE =
  "Typ kann nicht geändert werden. Bitte alten Eintrag löschen und neuen anlegen.";
const WORK_EVENT_NOT_FOUND_DE = "WorkEvent nicht gefunden";

// ── Phase 79 Plan 02 — query schema + range resolution ─────────────────────
// listQuerySchema is the shared shape for GET /mine and GET / (management).
// /mine intentionally IGNORES `employeeId` from the query — self-scope is
// always derived from req.user.employeeId. Parsing the field on both endpoints
// keeps the validation surface uniform.
const listQuerySchema = z.object({
  from: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "from muss im Format YYYY-MM-DD sein")
    .optional(),
  to: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "to muss im Format YYYY-MM-DD sein")
    .optional(),
  employeeId: z.string().uuid("employeeId muss eine UUID sein").optional(),
});

// Default window when neither from nor to is supplied. Mirrors the
// vocational-school /upcoming default (90 days forward).
const DEFAULT_RANGE_DAYS = 90;

// REVISION (W2): German message for the half-window rejection path.
const HALF_WINDOW_ERROR_DE = "from und to müssen zusammen angegeben werden";

/**
 * Sentinel return value type — either a resolved date range, or a "reject this
 * request" signal that the caller maps to HTTP 400 with HALF_WINDOW_ERROR_DE.
 *
 * REVISION (W2): introduced so resolveRange() never silently fills in a missing
 * bound.
 */
type RangeResolution = { kind: "ok"; from: Date; to: Date } | { kind: "half-window-rejected" };

function resolveRange(q: z.infer<typeof listQuerySchema>): RangeResolution {
  // REVISION (W2): reject half-window queries explicitly. If only one bound was
  // supplied, the client is asking for something ambiguous — drop the request.
  if ((q.from && !q.to) || (!q.from && q.to)) {
    return { kind: "half-window-rejected" };
  }
  if (q.from && q.to) {
    return {
      kind: "ok",
      from: new Date(q.from + "T00:00:00.000Z"),
      to: new Date(q.to + "T00:00:00.000Z"),
    };
  }
  // Default window: [today, today+90] UTC.
  const today = new Date();
  const from = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()));
  const to = new Date(from.getTime() + DEFAULT_RANGE_DAYS * 24 * 60 * 60 * 1000);
  return { kind: "ok", from, to };
}

export async function workEventRoutes(app: FastifyInstance) {
  // Per-route preHandler (NOT global addHook) — CodeQL js/missing-rate-limiting
  // detects rate limiting reliably when auth + rateLimit live on the same route
  // definition (matches the time-entries.ts pattern).

  // ── GET /api/v1/work-events/mine — self-view (any authenticated user) ──────
  // E-1/E-2/E-3 mitigation: structurally separate from the management surface.
  // Wired in Phase 79 Plan 02 — see 79-02-PLAN.md.
  // Self-scope is enforced by the URL path + req.user.employeeId. The handler
  // never inspects the caller's role and never reads the employeeId query
  // parameter for scoping — that makes the v1.8.12 cross-employee leak class
  // structurally impossible.
  app.get("/mine", {
    schema: { tags: ["WorkEvents"], security: [{ bearerAuth: [] }] },
    config: { rateLimit: READ_RATE_LIMIT },
    preHandler: requireAuth,
    handler: async (req, reply) => {
      const q = listQuerySchema.parse(req.query);
      // REVISION (W2): reject half-window queries before any other work.
      const range = resolveRange(q);
      if (range.kind === "half-window-rejected") {
        return reply.code(400).send({ error: HALF_WINDOW_ERROR_DE });
      }
      // SELF-SCOPE — derived from JWT. req.query.employeeId is intentionally ignored.
      if (!req.user.employeeId) {
        // User without linked Employee row sees nothing. 200 + [] (not 4xx) so the
        // frontend can render an empty list without a noisy error toast. Mirrors
        // the vocational-school.ts:144-148 convention.
        return reply.code(200).send([]);
      }
      const { from, to } = range;
      const rows = await app.prisma.workEvent.findMany({
        where: {
          employeeId: req.user.employeeId,
          deletedAt: null,
          date: { gte: from, lte: to },
        },
        select: {
          id: true,
          employeeId: true,
          type: true,
          source: true,
          date: true,
          workedMinutes: true,
          expectedMinutes: true,
          payload: true,
          note: true,
        },
        orderBy: { date: "asc" },
      });
      // ISO-date the date field so the type signature stays JSON-stable.
      return reply.code(200).send(
        rows.map((r) => ({
          ...r,
          date: r.date.toISOString().slice(0, 10),
        })),
      );
    },
  });

  // ── GET /api/v1/work-events — management list (ADMIN/MANAGER) ──────────────
  // Wired in Phase 79 Plan 02 — see 79-02-PLAN.md.
  // Tenant-scoped via the `employee: { tenantId }` relation join (WorkEvent has
  // no denormalized tenantId column). Optional ?employeeId= narrows within the
  // caller's tenant. EMPLOYEE is rejected by the requireRole preHandler before
  // the handler runs.
  app.get("/", {
    schema: { tags: ["WorkEvents"], security: [{ bearerAuth: [] }] },
    config: { rateLimit: READ_RATE_LIMIT },
    preHandler: requireRole("ADMIN", "MANAGER"),
    handler: async (req, reply) => {
      const q = listQuerySchema.parse(req.query);
      // REVISION (W2): half-window rejection applies symmetrically to the
      // management surface.
      const range = resolveRange(q);
      if (range.kind === "half-window-rejected") {
        return reply.code(400).send({ error: HALF_WINDOW_ERROR_DE });
      }
      const { from, to } = range;
      const rows = await app.prisma.workEvent.findMany({
        where: {
          deletedAt: null,
          date: { gte: from, lte: to },
          // Tenant isolation — join on Employee.tenantId.
          employee: { tenantId: req.user.tenantId },
          ...(q.employeeId ? { employeeId: q.employeeId } : {}),
        },
        select: {
          id: true,
          employeeId: true,
          type: true,
          source: true,
          date: true,
          workedMinutes: true,
          expectedMinutes: true,
          payload: true,
          note: true,
          employee: { select: { firstName: true, lastName: true, employeeNumber: true } },
        },
        orderBy: [{ date: "asc" }, { employeeId: "asc" }],
      });
      return reply.code(200).send(
        rows.map((r) => ({
          ...r,
          date: r.date.toISOString().slice(0, 10),
        })),
      );
    },
  });

  // ── POST /api/v1/work-events — manual create (ADMIN/MANAGER) ───────────────
  // Wired in Phase 79 Plan 03 — see 79-03-PLAN.md.
  // Gate order (mirrors vocational-school.ts:203-313):
  //   1. Zod parse + payload.type ↔ body.type consistency + workEventPayloadSchema
  //   2. Cross-tenant employee lookup → 404 (NOT 403; avoids existence leak)
  //   3. AZUBI/classification gate via assertClassificationAllowed (data-driven)
  //   4. Locked-month gate via assertMonthNotLocked (REVISION B2: STRING input)
  //   5. INSERT — DB-level @@unique([employeeId, date, type]) → P2002 → 409
  //   6. AuditLog WORK_EVENT_CREATED with newValue snapshot
  app.post("/", {
    schema: { tags: ["WorkEvents"], security: [{ bearerAuth: [] }] },
    config: { rateLimit: WRITE_RATE_LIMIT },
    preHandler: requireRole("ADMIN", "MANAGER"),
    handler: async (req, reply) => {
      const tenantId = req.user.tenantId;
      const body = createBodySchema.parse(req.body);
      // REVISION (B2): we DO compute dateUtc for the Prisma write call (the @db.Date
      // column needs a Date), but we pass body.date (the STRING) to the locked-month
      // helper so month resolution is string-based, not Date-arithmetic-based.
      const dateUtc = new Date(body.date + "T00:00:00.000Z");

      // (1) Payload consistency + Zod discriminated-union validation.
      if (body.payload !== undefined && body.payload !== null) {
        const payload = body.payload as { type?: unknown };
        if (payload.type !== body.type) {
          return reply.code(400).send({
            error: "Validierungsfehler",
            message: "payload.type muss dem WorkEvent type entsprechen",
          });
        }
        workEventPayloadSchema.parse(body.payload);
      }

      // (2) Cross-tenant employee lookup. 404 (NOT 403) to avoid leaking existence.
      const employee = await app.prisma.employee.findFirst({
        where: { id: body.employeeId, tenantId },
        select: { id: true, classification: true },
      });
      if (!employee) {
        return reply.code(404).send({ error: EMPLOYEE_NOT_FOUND_DE });
      }

      // (3) AZUBI / classification gate — data-driven via workEventTypeRules.
      try {
        assertClassificationAllowed(body.type, employee.classification);
      } catch (err) {
        if (err instanceof ClassificationNotAllowedError) {
          return reply.code(err.statusCode).send({ error: err.message });
        }
        throw err;
      }

      // (4) Locked-month gate.
      // REVISION (B2): pass body.date (YYYY-MM-DD string) directly — NOT dateUtc.
      // The helper parses year/month from the string for TZ-edge correctness.
      const tz = await getTenantTimezone(app.prisma, tenantId);
      try {
        await assertMonthNotLocked(app.prisma, employee.id, body.date, tz);
      } catch (err) {
        if (err instanceof LockedMonthError) {
          return reply.code(err.statusCode).send({ error: LOCKED_MONTH_ERROR_DE });
        }
        throw err;
      }

      // (5) Create + (6) AuditLog. P2002 → 409.
      try {
        const created = await app.prisma.workEvent.create({
          data: {
            employeeId: employee.id,
            type: body.type,
            source: body.source,
            date: dateUtc,
            workedMinutes: body.workedMinutes,
            expectedMinutes: body.expectedMinutes ?? null,
            payload: body.payload as Prisma.InputJsonValue | undefined,
            note: body.note ?? null,
            createdBy: req.user.sub,
          },
        });

        await app.audit({
          userId: req.user.sub,
          action: "WORK_EVENT_CREATED",
          entity: "WorkEvent",
          entityId: created.id,
          newValue: {
            employeeId: created.employeeId,
            date: body.date,
            type: created.type,
            source: created.source,
            workedMinutes: created.workedMinutes,
            expectedMinutes: created.expectedMinutes,
          },
          request: { ip: req.ip, headers: req.headers as Record<string, string> },
        });

        return reply.code(201).send({
          ...created,
          date: created.date.toISOString().slice(0, 10),
        });
      } catch (err: unknown) {
        if (
          typeof err === "object" &&
          err !== null &&
          "code" in err &&
          (err as { code: unknown }).code === "P2002"
        ) {
          return reply.code(409).send({ error: DUPLICATE_WORK_EVENT_DE });
        }
        throw err;
      }
    },
  });

  // ── PATCH /api/v1/work-events/:id — edit (ADMIN/MANAGER) ───────────────────
  // Wired in Phase 79 Plan 03 — see 79-03-PLAN.md.
  // Gate order:
  //   0. type-immutability detection (returns 400 BEFORE the general body parse
  //      so the client gets a domain-specific error instead of "unrecognized key")
  //   1. Zod parse on body + tenant-scoped existence check → 404 if missing
  //   2. Payload re-validation if present
  //   3. Locked-month gate on BOTH the candidate date AND the existing date
  //      (REVISION B2: pass YYYY-MM-DD strings, never Date objects)
  //   4. UPDATE — only mutate fields that were sent (partial update)
  //   5. AuditLog WORK_EVENT_UPDATED with full old/new snapshots
  app.patch("/:id", {
    schema: { tags: ["WorkEvents"], security: [{ bearerAuth: [] }] },
    config: { rateLimit: WRITE_RATE_LIMIT },
    preHandler: requireRole("ADMIN", "MANAGER"),
    handler: async (req, reply) => {
      const tenantId = req.user.tenantId;
      const { id } = idParamSchema.parse(req.params);

      // (0) Explicit type-immutability check BEFORE general body parse so the
      // client gets a domain-specific 400, not a generic "unknown key" error.
      const typeDetect = updateBodyDetectTypeSchema.parse(req.body);
      if (typeDetect.type !== undefined) {
        return reply.code(400).send({ error: TYPE_IMMUTABLE_DE });
      }

      const body = updateBodySchema.parse(req.body);

      // (1) Tenant-scoped existence check + load oldValue snapshot.
      const existing = await app.prisma.workEvent.findFirst({
        where: {
          id,
          deletedAt: null,
          employee: { tenantId },
        },
        select: {
          id: true,
          employeeId: true,
          type: true,
          source: true,
          date: true,
          workedMinutes: true,
          expectedMinutes: true,
          payload: true,
          note: true,
        },
      });
      if (!existing) {
        return reply.code(404).send({ error: WORK_EVENT_NOT_FOUND_DE });
      }

      // (2) Payload re-validation if present in body.
      if (body.payload !== undefined && body.payload !== null) {
        const payload = body.payload as { type?: unknown };
        if (payload.type !== existing.type) {
          return reply.code(400).send({
            error: "Validierungsfehler",
            message: "payload.type muss dem WorkEvent type entsprechen",
          });
        }
        workEventPayloadSchema.parse(body.payload);
      }

      // (3) Locked-month gate — Revisionssicherheit: a row whose existing
      // month is sealed is immutable, full stop. Only when the existing month
      // is unlocked do we also gate the candidate month (so a date-move into
      // a sealed month is rejected too).
      //
      // WR-03 (Phase 79 review): gate on the EXISTING month FIRST so the
      // conservative invariant is enforced before we consider the move
      // target. Previously the candidate was gated first, which produced the
      // same correct 4xx outcome but inverted the ordering relative to the
      // "you can't mutate a row whose existing month is sealed" reading.
      //
      // REVISION (B2): pass the YYYY-MM-DD string. For body.date use it directly;
      // for existing.date convert via toISOString().slice(0,10) so the helper
      // receives a YYYY-MM-DD string regardless of branch.
      const tz = await getTenantTimezone(app.prisma, tenantId);
      // @db.Date columns come back as UTC midnight from Prisma — slicing
      // toISOString() at 10 chars always yields the row's calendar day in UTC,
      // matching how the row was originally written. Safe for assertMonthNotLocked.
      const existingDateStr = existing.date.toISOString().slice(0, 10);
      const candidateDateStr = body.date ?? existingDateStr;
      const candidateDate = body.date ? new Date(body.date + "T00:00:00.000Z") : existing.date;
      try {
        await assertMonthNotLocked(app.prisma, existing.employeeId, existingDateStr, tz);
      } catch (err) {
        if (err instanceof LockedMonthError) {
          return reply.code(err.statusCode).send({ error: LOCKED_MONTH_ERROR_DE });
        }
        throw err;
      }

      // Also gate the candidate month if date is being moved INTO a different
      // month — Revisionssicherheit: a row cannot land IN a sealed month
      // either. Skip the redundant lookup when the date isn't moving.
      if (body.date && candidateDateStr !== existingDateStr) {
        try {
          await assertMonthNotLocked(app.prisma, existing.employeeId, candidateDateStr, tz);
        } catch (err) {
          if (err instanceof LockedMonthError) {
            return reply.code(err.statusCode).send({ error: LOCKED_MONTH_ERROR_DE });
          }
          throw err;
        }
      }

      // (4) UPDATE — partial update; only mutate fields that were actually sent.
      try {
        const updated = await app.prisma.workEvent.update({
          where: { id: existing.id },
          data: {
            ...(body.date !== undefined ? { date: candidateDate } : {}),
            ...(body.source !== undefined ? { source: body.source } : {}),
            ...(body.workedMinutes !== undefined ? { workedMinutes: body.workedMinutes } : {}),
            ...(body.expectedMinutes !== undefined
              ? { expectedMinutes: body.expectedMinutes }
              : {}),
            ...(body.payload !== undefined
              ? { payload: body.payload as Prisma.InputJsonValue }
              : {}),
            ...(body.note !== undefined ? { note: body.note } : {}),
          },
        });

        await app.audit({
          userId: req.user.sub,
          action: "WORK_EVENT_UPDATED",
          entity: "WorkEvent",
          entityId: updated.id,
          oldValue: {
            date: existingDateStr,
            source: existing.source,
            workedMinutes: existing.workedMinutes,
            expectedMinutes: existing.expectedMinutes,
            payload: existing.payload,
            note: existing.note,
          },
          newValue: {
            date: updated.date.toISOString().slice(0, 10),
            source: updated.source,
            workedMinutes: updated.workedMinutes,
            expectedMinutes: updated.expectedMinutes,
            payload: updated.payload,
            note: updated.note,
          },
          request: { ip: req.ip, headers: req.headers as Record<string, string> },
        });

        return reply.code(200).send({
          ...updated,
          date: updated.date.toISOString().slice(0, 10),
        });
      } catch (err: unknown) {
        if (
          typeof err === "object" &&
          err !== null &&
          "code" in err &&
          (err as { code: unknown }).code === "P2002"
        ) {
          return reply.code(409).send({ error: DUPLICATE_WORK_EVENT_DE });
        }
        throw err;
      }
    },
  });

  // ── DELETE /api/v1/work-events/:id — soft-delete (ADMIN/MANAGER) ───────────
  // Wired in Phase 79 Plan 03 — see 79-03-PLAN.md.
  // Gates:
  //   1. Tenant-scoped existence check (excludes soft-deleted rows) → 404
  //   2. Locked-month gate on the existing row's month
  //      (REVISION B2: pass existing.date as YYYY-MM-DD string)
  //   3. Soft-delete via `deletedAt: new Date()` — NEVER prisma.workEvent.delete
  //      (Revisionssicherheit; Test D8 asserts the row stays in the DB)
  //   4. AuditLog WORK_EVENT_DELETED with oldValue snapshot
  app.delete("/:id", {
    schema: { tags: ["WorkEvents"], security: [{ bearerAuth: [] }] },
    config: { rateLimit: WRITE_RATE_LIMIT },
    preHandler: requireRole("ADMIN", "MANAGER"),
    handler: async (req, reply) => {
      const tenantId = req.user.tenantId;
      const { id } = idParamSchema.parse(req.params);

      // (1) Tenant-scoped existence check + load oldValue.
      const existing = await app.prisma.workEvent.findFirst({
        where: {
          id,
          deletedAt: null,
          employee: { tenantId },
        },
        select: {
          id: true,
          employeeId: true,
          type: true,
          source: true,
          date: true,
          workedMinutes: true,
          expectedMinutes: true,
          payload: true,
          note: true,
        },
      });
      if (!existing) {
        return reply.code(404).send({ error: WORK_EVENT_NOT_FOUND_DE });
      }

      // (2) Locked-month gate.
      // REVISION (B2): convert existing.date to YYYY-MM-DD string for the helper.
      const tz = await getTenantTimezone(app.prisma, tenantId);
      const existingDateStr = existing.date.toISOString().slice(0, 10);
      try {
        await assertMonthNotLocked(app.prisma, existing.employeeId, existingDateStr, tz);
      } catch (err) {
        if (err instanceof LockedMonthError) {
          return reply.code(err.statusCode).send({ error: LOCKED_MONTH_ERROR_DE });
        }
        throw err;
      }

      // (3) Soft delete. WorkEvent has no deletedBy column — deleter is in AuditLog.
      await app.prisma.workEvent.update({
        where: { id: existing.id },
        data: { deletedAt: new Date() },
      });

      // (4) Audit trail.
      await app.audit({
        userId: req.user.sub,
        action: "WORK_EVENT_DELETED",
        entity: "WorkEvent",
        entityId: existing.id,
        oldValue: {
          employeeId: existing.employeeId,
          date: existingDateStr,
          type: existing.type,
          source: existing.source,
          workedMinutes: existing.workedMinutes,
          expectedMinutes: existing.expectedMinutes,
          payload: existing.payload,
          note: existing.note,
        },
        request: { ip: req.ip, headers: req.headers as Record<string, string> },
      });

      return reply.code(204).send();
    },
  });
}
